# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go


on:
  push:
    tags:
      - "v*.*.*"
jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      # dir D:\a\demo\demo
    - shell: cmd
      run: dir
    
    - shell: cmd
      run: echo asd>a.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      token: ${{ github.token }}
      with:
        files: a.txt